/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../src/layout/AppLayout.vue')['default']
    AppLogo: typeof import('./../src/layout/AppLogo.vue')['default']
    AppMenu: typeof import('./../src/layout/AppMenu.vue')['default']
    AppMenuItem: typeof import('./../src/layout/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./../src/layout/AppSidebar.vue')['default']
    AppUser: typeof import('./../src/layout/AppUser.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    Dock: typeof import('primevue/dock')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
