/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./../src/layout/header/AppBreadcrumb.vue')['default']
    AppHandleBar: typeof import('./../src/layout/header/AppHandleBar.vue')['default']
    AppHeader: typeof import('./../src/layout/header/AppHeader.vue')['default']
    AppLayout: typeof import('./../src/layout/AppLayout.vue')['default']
    AppLogo: typeof import('./../src/layout/sider/AppLogo.vue')['default']
    AppMenu: typeof import('./../src/layout/sider/AppMenu.vue')['default']
    AppMenuItem: typeof import('./../src/layout/sider/AppMenuItem.vue')['default']
    AppSettings: typeof import('./../src/layout/header/AppSettings.vue')['default']
    AppSidebar: typeof import('./../src/layout/sider/AppSidebar.vue')['default']
    AppUser: typeof import('./../src/layout/sider/AppUser.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
